# Generated by Powerlevel10k configuration wizard for forest-elegance theme
# Based on the green color palette with natural forest design
# Colors: #022b22 (dark forest), #275d46 (medium forest), #569578 (light forest), #101c13 (deep shadow)

# Temporarily change options.
'builtin' 'local' '-a' 'p10k_config_opts'
[[ ! -o 'aliases'         ]] || p10k_config_opts+=('aliases')
[[ ! -o 'sh_glob'         ]] || p10k_config_opts+=('sh_glob')
[[ ! -o 'no_brace_expand' ]] || p10k_config_opts+=('no_brace_expand')
'builtin' 'setopt' 'no_aliases' 'no_sh_glob' 'brace_expand'

() {
  emulate -L zsh -o extended_glob

  # Unset all configuration options.
  unset -m '(POWERLEVEL9K_*|DEFAULT_USER)~POWERLEVEL9K_GITSTATUS_DIR'

  # Zsh >= 5.1 is required.
  [[ $ZSH_VERSION == (5.<1->*|<6->.*) ]] || return

  # The list of segments shown on the left.
  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    # =========================[ Line #1 ]=========================
    os_icon                 # os identifier
    dir                     # current directory
    vcs                     # git status
    # =========================[ Line #2 ]=========================
    newline                 # \n
    prompt_char             # prompt symbol
  )

  # The list of segments shown on the right.
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
    # =========================[ Line #1 ]=========================
    status                  # exit code of the last command
    command_execution_time  # duration of the last command
    background_jobs         # presence of background jobs
    virtualenv              # python virtual environment
    pyenv                   # python environment
    nvm                     # node.js version from nvm
    context                 # user@hostname
    # =========================[ Line #2 ]=========================
    newline
    time                    # current time
  )

  # Defines character set used by powerlevel10k.
  typeset -g POWERLEVEL9K_MODE=nerdfont-complete
  typeset -g POWERLEVEL9K_ICON_PADDING=none

  # Icons go before content.
  typeset -g POWERLEVEL9K_ICON_BEFORE_CONTENT=true

  # Add an empty line before each prompt.
  typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=true

  # Connect left prompt lines with elegant symbols using medium forest green.
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX='%65F╭─'
  typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_PREFIX='%65F├─'
  typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX='%65F╰─'
  # Connect right prompt lines with these symbols.
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_SUFFIX='%65F─╮'
  typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_SUFFIX='%65F─┤'
  typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_SUFFIX='%65F─╯'

  # Filler between left and right prompt.
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_CHAR='·'
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_BACKGROUND=
  typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_GAP_BACKGROUND=
  if [[ $POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_CHAR != ' ' ]]; then
    typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_FOREGROUND=65
    typeset -g POWERLEVEL9K_EMPTY_LINE_LEFT_PROMPT_FIRST_SEGMENT_END_SYMBOL='%{%}'
    typeset -g POWERLEVEL9K_EMPTY_LINE_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL='%{%}'
  fi

  # Separators
  typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='\uE0B1'
  typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR='\uE0B3'
  typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR='\uE0B0'
  typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR='\uE0B2'

  typeset -g POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL='\uE0B0'
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL='\uE0B2'
  typeset -g POWERLEVEL9K_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL=''
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL=''
  typeset -g POWERLEVEL9K_EMPTY_LINE_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=

  #################################[ os_icon: os identifier ]##################################
  # OS identifier with elegant forest colors
  typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=22   # dark forest
  typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND=108  # light forest

  ################################[ prompt_char: prompt symbol ]################################
  typeset -g POWERLEVEL9K_PROMPT_CHAR_BACKGROUND=
  # Success: light forest, Error: medium forest for natural contrast
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=108
  typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=65
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION='❯'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VICMD_CONTENT_EXPANSION='❮'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIVIS_CONTENT_EXPANSION='V'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIOWR_CONTENT_EXPANSION='▶'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OVERWRITE_STATE=true
  typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=
  typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL=
  typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_{LEFT,RIGHT}_WHITESPACE=

  ##################################[ dir: current directory ]##################################
  typeset -g POWERLEVEL9K_DIR_BACKGROUND=65       # medium forest
  typeset -g POWERLEVEL9K_DIR_FOREGROUND=108      # light forest
  typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
  typeset -g POWERLEVEL9K_SHORTEN_DELIMITER=
  typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=107    # slightly darker light forest
  typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=108       # light forest
  typeset -g POWERLEVEL9K_DIR_ANCHOR_BOLD=true
  
  local anchor_files=(
    .bzr .citc .git .hg .node-version .python-version .go-version .ruby-version
    .lua-version .java-version .perl-version .php-version .tool-versions
    .shorten_folder_marker .svn .terraform CVS Cargo.toml composer.json
    go.mod package.json stack.yaml
  )
  typeset -g POWERLEVEL9K_SHORTEN_FOLDER_MARKER="(${(j:|:)anchor_files})"
  typeset -g POWERLEVEL9K_DIR_TRUNCATE_BEFORE_MARKER=false
  typeset -g POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
  typeset -g POWERLEVEL9K_DIR_MAX_LENGTH=80
  typeset -g POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS=40
  typeset -g POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS_PCT=50
  typeset -g POWERLEVEL9K_DIR_HYPERLINK=false
  typeset -g POWERLEVEL9K_DIR_SHOW_WRITABLE=v3

  #####################################[ vcs: git status ]####################################
  typeset -g POWERLEVEL9K_VCS_BRANCH_ICON='\uF126 '
  
  # Clean repository colors - light and fresh like new growth
  typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=22         # dark forest
  typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND=108        # light forest
  
  # Untracked files - deeper forest colors
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=108    # light forest
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND=65     # medium forest
  
  # Modified files - natural earth tones
  typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=22      # dark forest
  typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND=107     # slightly darker light forest
  
  # Staged files - ready for harvest
  typeset -g POWERLEVEL9K_VCS_STAGED_FOREGROUND=108       # light forest
  typeset -g POWERLEVEL9K_VCS_STAGED_BACKGROUND=65        # medium forest

  ##################################[ status: exit code ]#################################
  typeset -g POWERLEVEL9K_STATUS_EXTENDED_STATES=true
  typeset -g POWERLEVEL9K_STATUS_OK=false
  typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND=108        # light forest
  typeset -g POWERLEVEL9K_STATUS_OK_BACKGROUND=22         # dark forest
  typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=108     # light forest
  typeset -g POWERLEVEL9K_STATUS_ERROR_BACKGROUND=65      # medium forest

  ###################[ command_execution_time: duration of the last command ]###################
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=3
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=0
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=22    # dark forest
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=108   # light forest

  #######################[ background_jobs: presence of background jobs ]#######################
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=false
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND=108          # light forest
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND=65           # medium forest

  ##########[ virtualenv: python virtual environment (https://docs.python.org/3/library/venv.html) ]##########
  typeset -g POWERLEVEL9K_VIRTUALENV_FOREGROUND=22                # dark forest
  typeset -g POWERLEVEL9K_VIRTUALENV_BACKGROUND=108               # light forest
  typeset -g POWERLEVEL9K_VIRTUALENV_SHOW_PYTHON_VERSION=false
  typeset -g POWERLEVEL9K_VIRTUALENV_{LEFT,RIGHT}_DELIMITER=

  ################[ pyenv: python environment (https://github.com/pyenv/pyenv) ]################
  typeset -g POWERLEVEL9K_PYENV_FOREGROUND=108                    # light forest
  typeset -g POWERLEVEL9K_PYENV_BACKGROUND=65                     # medium forest

  ################[ nvm: node.js version from nvm (https://github.com/nvm-sh/nvm) ]################
  typeset -g POWERLEVEL9K_NVM_FOREGROUND=22                       # dark forest
  typeset -g POWERLEVEL9K_NVM_BACKGROUND=108                      # light forest

  #[ context: user@hostname ]#
  typeset -g POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND=108             # light forest
  typeset -g POWERLEVEL9K_CONTEXT_ROOT_BACKGROUND=65              # medium forest
  typeset -g POWERLEVEL9K_CONTEXT_{REMOTE,REMOTE_SUDO}_FOREGROUND=22   # dark forest
  typeset -g POWERLEVEL9K_CONTEXT_{REMOTE,REMOTE_SUDO}_BACKGROUND=108  # light forest
  typeset -g POWERLEVEL9K_CONTEXT_FOREGROUND=65                   # medium forest
  typeset -g POWERLEVEL9K_CONTEXT_BACKGROUND=108                  # light forest

  #####################[ time: current time ]#####################
  typeset -g POWERLEVEL9K_TIME_FOREGROUND=22                      # dark forest
  typeset -g POWERLEVEL9K_TIME_BACKGROUND=108                     # light forest
  typeset -g POWERLEVEL9K_TIME_FORMAT='%D{%H:%M:%S}'

  # Instant prompt mode.
  typeset -g POWERLEVEL9K_INSTANT_PROMPT=verbose

  # Hot reload.
  typeset -g POWERLEVEL9K_DISABLE_HOT_RELOAD=true

  # If p10k is already loaded, reload configuration.
  (( ! $+functions[p10k] )) || p10k reload
}

# Tell `p10k configure` which file it should overwrite.
typeset -g POWERLEVEL9K_CONFIG_FILE=${${(%):-%x}:a}

(( ${#p10k_config_opts} )) && setopt ${p10k_config_opts[@]}
'builtin' 'unset' 'p10k_config_opts'